name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: ["1.80.0", "1.81.0", "1.82.0", "stable"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Display Rust version
        run: rustc --version

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test
